// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_red;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_dig5;
lv_obj_t * ui_red1;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_dig6;
lv_obj_t * ui_black1;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_dig1;
lv_obj_t * ui_black2;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_dig2;
lv_obj_t * ui_black3;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_dig3;
lv_obj_t * ui_black4;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_dig4;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
lv_obj_t * ui_lineRed;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Panel13;
lv_obj_t * ui_Panel14;
lv_obj_t * ui_Label4;
void ui_event_Panel16(lv_event_t * e);
lv_obj_t * ui_Panel16;
lv_obj_t * ui_Panel17;
lv_obj_t * ui_Panel18;
lv_obj_t * ui_Panel19;
lv_obj_t * ui_Label11;
lv_obj_t * ui_line1;
lv_obj_t * ui_line2;
lv_obj_t * ui_line3;
lv_obj_t * ui_line4;
lv_obj_t * ui_line5;
lv_obj_t * ui_line6;
lv_obj_t * ui_line7;
lv_obj_t * ui_line8;
lv_obj_t * ui_Panel21;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Label5;
void ui_event_okBut(lv_event_t * e);
lv_obj_t * ui_okBut;
lv_obj_t * ui_Label6;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label10;
lv_obj_t * ui_setHr;
lv_obj_t * ui_setMin;
void ui_event_hrUp(lv_event_t * e);
lv_obj_t * ui_hrUp;
lv_obj_t * ui_dsff;
void ui_event_minUp(lv_event_t * e);
lv_obj_t * ui_minUp;
lv_obj_t * ui_Label13;
void ui_event_hrDown(lv_event_t * e);
lv_obj_t * ui_hrDown;
lv_obj_t * ui_Label14;
void ui_event_minDown(lv_event_t * e);
lv_obj_t * ui_minDown;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Panel15;
lv_obj_t * ui_Panel20;
void ui_event_Switch1(lv_event_t * e);
lv_obj_t * ui_Switch1;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label16;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_logo[1] = {&ui_img_logo2_png};
const lv_img_dsc_t * ui_imgset_poz[1] = {&ui_img_poz1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Panel16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setTimeScreen(e);
    }
}
void ui_event_okBut(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        timeSetF(e);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_hrUp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        timeSetF(e);
    }
}
void ui_event_minUp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        timeSetF(e);
    }
}
void ui_event_hrDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        timeSetF(e);
    }
}
void ui_event_minDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        timeSetF(e);
    }
}
void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        setTimeFormat(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
