// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_red;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_dig5;
extern lv_obj_t * ui_red1;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_dig6;
extern lv_obj_t * ui_black1;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_dig1;
extern lv_obj_t * ui_black2;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_dig2;
extern lv_obj_t * ui_black3;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_dig3;
extern lv_obj_t * ui_black4;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_dig4;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_lineRed;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Label4;
void ui_event_Panel16(lv_event_t * e);
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_line1;
extern lv_obj_t * ui_line2;
extern lv_obj_t * ui_line3;
extern lv_obj_t * ui_line4;
extern lv_obj_t * ui_line5;
extern lv_obj_t * ui_line6;
extern lv_obj_t * ui_line7;
extern lv_obj_t * ui_line8;
extern lv_obj_t * ui_Panel21;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Label5;
void ui_event_okBut(lv_event_t * e);
extern lv_obj_t * ui_okBut;
extern lv_obj_t * ui_Label6;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_setHr;
extern lv_obj_t * ui_setMin;
void ui_event_hrUp(lv_event_t * e);
extern lv_obj_t * ui_hrUp;
extern lv_obj_t * ui_dsff;
void ui_event_minUp(lv_event_t * e);
extern lv_obj_t * ui_minUp;
extern lv_obj_t * ui_Label13;
void ui_event_hrDown(lv_event_t * e);
extern lv_obj_t * ui_hrDown;
extern lv_obj_t * ui_Label14;
void ui_event_minDown(lv_event_t * e);
extern lv_obj_t * ui_minDown;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Panel20;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_logo2_png);    // assets\logo2.png
LV_IMG_DECLARE(ui_img_rightback_png);    // assets\rightBack.png
LV_IMG_DECLARE(ui_img_poz1_png);    // assets\poz1.png

LV_FONT_DECLARE(ui_font_Font1);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
