// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -119);
    lv_obj_set_y(ui_Label5, -188);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Set Time");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x93A7B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_okBut = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_okBut, 158);
    lv_obj_set_height(ui_okBut, 67);
    lv_obj_set_x(ui_okBut, 125);
    lv_obj_set_y(ui_okBut, 183);
    lv_obj_set_align(ui_okBut, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_okBut, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_okBut, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_okBut, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_okBut, lv_color_hex(0x08451B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_okBut, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_okBut);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "OK");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button2, 158);
    lv_obj_set_height(ui_Button2, 67);
    lv_obj_set_x(ui_Button2, -126);
    lv_obj_set_y(ui_Button2, 182);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x790101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "BACK");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setHr = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_setHr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setHr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setHr, -98);
    lv_obj_set_y(ui_setHr, 0);
    lv_obj_set_align(ui_setHr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_setHr, "00");
    lv_obj_set_style_text_font(ui_setHr, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setMin = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_setMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setMin, 90);
    lv_obj_set_y(ui_setMin, 0);
    lv_obj_set_align(ui_setMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_setMin, "00");
    lv_obj_set_style_text_font(ui_setMin, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hrUp = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_hrUp, 81);
    lv_obj_set_height(ui_hrUp, 78);
    lv_obj_set_x(ui_hrUp, -98);
    lv_obj_set_y(ui_hrUp, -84);
    lv_obj_set_align(ui_hrUp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hrUp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_hrUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_hrUp, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_hrUp, lv_color_hex(0x3C4457), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hrUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dsff = lv_label_create(ui_hrUp);
    lv_obj_set_width(ui_dsff, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dsff, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_dsff, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dsff, "+");
    lv_obj_set_style_text_font(ui_dsff, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minUp = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_minUp, 81);
    lv_obj_set_height(ui_minUp, 78);
    lv_obj_set_x(ui_minUp, 90);
    lv_obj_set_y(ui_minUp, -84);
    lv_obj_set_align(ui_minUp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_minUp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_minUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_minUp, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_minUp, lv_color_hex(0x3C4457), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_minUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_minUp);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "+");
    lv_obj_set_style_text_font(ui_Label13, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hrDown = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_hrDown, 81);
    lv_obj_set_height(ui_hrDown, 78);
    lv_obj_set_x(ui_hrDown, -98);
    lv_obj_set_y(ui_hrDown, 79);
    lv_obj_set_align(ui_hrDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hrDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_hrDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_hrDown, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_hrDown, lv_color_hex(0x3C4457), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hrDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_hrDown);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "-");
    lv_obj_set_style_text_font(ui_Label14, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minDown = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_minDown, 81);
    lv_obj_set_height(ui_minDown, 78);
    lv_obj_set_x(ui_minDown, 90);
    lv_obj_set_y(ui_minDown, 77);
    lv_obj_set_align(ui_minDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_minDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_minDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_minDown, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_minDown, lv_color_hex(0x3C4457), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_minDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_minDown);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "-");
    lv_obj_set_style_text_font(ui_Label15, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel15 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel15, 6);
    lv_obj_set_height(ui_Panel15, 6);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0xD4CECE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel20 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel20, 6);
    lv_obj_set_height(ui_Panel20, 6);
    lv_obj_set_x(ui_Panel20, 0);
    lv_obj_set_y(ui_Panel20, -13);
    lv_obj_set_align(ui_Panel20, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel20, lv_color_hex(0xD4CECE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Screen2);
    lv_obj_set_width(ui_Switch1, 91);
    lv_obj_set_height(ui_Switch1, 42);
    lv_obj_set_x(ui_Switch1, 140);
    lv_obj_set_y(ui_Switch1, -189);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);


    ui_Label12 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 69);
    lv_obj_set_y(ui_Label12, -188);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "24H");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 209);
    lv_obj_set_y(ui_Label16, -189);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "12H");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_okBut, ui_event_okBut, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_hrUp, ui_event_hrUp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_minUp, ui_event_minUp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_hrDown, ui_event_hrDown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_minDown, ui_event_minDown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);

}
