// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_logo2_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel4, 48);
    lv_obj_set_height(ui_Panel4, 112);
    lv_obj_set_x(ui_Panel4, 75);
    lv_obj_set_y(ui_Panel4, -65);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xE9EAEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 237);
    lv_obj_set_height(ui_Panel1, 103);
    lv_obj_set_x(ui_Panel1, -59);
    lv_obj_set_y(ui_Panel1, -63);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x50575B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel1, lv_color_hex(0x373535), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 121);
    lv_obj_set_height(ui_Panel2, 100);
    lv_obj_set_x(ui_Panel2, 127);
    lv_obj_set_y(ui_Panel2, -62);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xE40908), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel2, lv_color_hex(0x780D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel5, 30);
    lv_obj_set_height(ui_Panel5, 30);
    lv_obj_set_x(ui_Panel5, 63);
    lv_obj_set_y(ui_Panel5, -9);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel6, 10);
    lv_obj_set_height(ui_Panel6, 10);
    lv_obj_set_x(ui_Panel6, 63);
    lv_obj_set_y(ui_Panel6, -9);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_red = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_red, 44);
    lv_obj_set_height(ui_red, 68);
    lv_obj_set_x(ui_red, 99);
    lv_obj_set_y(ui_red, -65);
    lv_obj_set_align(ui_red, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_red, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_red, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_red, lv_color_hex(0x5C0202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_red, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_red, lv_color_hex(0x680000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_red, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_red, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_red);
    lv_obj_set_width(ui_Panel3, 65);
    lv_obj_set_height(ui_Panel3, 37);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xA90808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dig5 = lv_label_create(ui_red);
    lv_obj_set_width(ui_dig5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dig5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dig5, 0);
    lv_obj_set_y(ui_dig5, 4);
    lv_obj_set_align(ui_dig5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dig5, "3");
    lv_obj_set_style_text_font(ui_dig5, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_red1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_red1, 44);
    lv_obj_set_height(ui_red1, 68);
    lv_obj_set_x(ui_red1, 149);
    lv_obj_set_y(ui_red1, -65);
    lv_obj_set_align(ui_red1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_red1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_red1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_red1, lv_color_hex(0x5C0202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_red1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_red1, lv_color_hex(0x680000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_red1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_red1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_red1);
    lv_obj_set_width(ui_Panel7, 65);
    lv_obj_set_height(ui_Panel7, 37);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xA90808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dig6 = lv_label_create(ui_red1);
    lv_obj_set_width(ui_dig6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dig6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dig6, 0);
    lv_obj_set_y(ui_dig6, 4);
    lv_obj_set_align(ui_dig6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dig6, "1");
    lv_obj_set_style_text_font(ui_dig6, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_black1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_black1, 44);
    lv_obj_set_height(ui_black1, 68);
    lv_obj_set_x(ui_black1, -141);
    lv_obj_set_y(ui_black1, -65);
    lv_obj_set_align(ui_black1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_black1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_black1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_black1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_black1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_black1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_black1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_black1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_black1);
    lv_obj_set_width(ui_Panel8, 65);
    lv_obj_set_height(ui_Panel8, 37);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x4C4D51), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dig1 = lv_label_create(ui_black1);
    lv_obj_set_width(ui_dig1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dig1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dig1, 0);
    lv_obj_set_y(ui_dig1, 4);
    lv_obj_set_align(ui_dig1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dig1, "0");
    lv_obj_set_style_text_font(ui_dig1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_black2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_black2, 44);
    lv_obj_set_height(ui_black2, 68);
    lv_obj_set_x(ui_black2, -88);
    lv_obj_set_y(ui_black2, -65);
    lv_obj_set_align(ui_black2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_black2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_black2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_black2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_black2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_black2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_black2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_black2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_black2);
    lv_obj_set_width(ui_Panel9, 65);
    lv_obj_set_height(ui_Panel9, 37);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x4C4D51), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dig2 = lv_label_create(ui_black2);
    lv_obj_set_width(ui_dig2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dig2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dig2, 0);
    lv_obj_set_y(ui_dig2, 4);
    lv_obj_set_align(ui_dig2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dig2, "5");
    lv_obj_set_style_text_font(ui_dig2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_black3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_black3, 44);
    lv_obj_set_height(ui_black3, 68);
    lv_obj_set_x(ui_black3, -28);
    lv_obj_set_y(ui_black3, -65);
    lv_obj_set_align(ui_black3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_black3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_black3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_black3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_black3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_black3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_black3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_black3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_black3);
    lv_obj_set_width(ui_Panel10, 65);
    lv_obj_set_height(ui_Panel10, 37);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x4C4D51), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dig3 = lv_label_create(ui_black3);
    lv_obj_set_width(ui_dig3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dig3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dig3, 0);
    lv_obj_set_y(ui_dig3, 4);
    lv_obj_set_align(ui_dig3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dig3, "2");
    lv_obj_set_style_text_font(ui_dig3, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_black4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_black4, 44);
    lv_obj_set_height(ui_black4, 68);
    lv_obj_set_x(ui_black4, 24);
    lv_obj_set_y(ui_black4, -65);
    lv_obj_set_align(ui_black4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_black4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_black4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_black4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_black4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_black4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_black4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_black4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_black4);
    lv_obj_set_width(ui_Panel11, 65);
    lv_obj_set_height(ui_Panel11, 37);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x4C4D51), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dig4 = lv_label_create(ui_black4);
    lv_obj_set_width(ui_dig4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dig4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dig4, 0);
    lv_obj_set_y(ui_dig4, 4);
    lv_obj_set_align(ui_dig4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dig4, "4");
    lv_obj_set_style_text_font(ui_dig4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, -143);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "kWh");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x2A2727), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -141);
    lv_obj_set_y(ui_Label8, -23);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "10000");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lineRed = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_lineRed, 48);
    lv_obj_set_height(ui_lineRed, 9);
    lv_obj_set_x(ui_lineRed, -19);
    lv_obj_set_y(ui_lineRed, 44);
    lv_obj_set_align(ui_lineRed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_lineRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_lineRed, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lineRed, lv_color_hex(0x980A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lineRed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lineRed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_lineRed);
    lv_obj_set_width(ui_Panel12, 45);
    lv_obj_set_height(ui_Panel12, 4);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0xAE4040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_rightback_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 69
    lv_obj_set_x(ui_Image2, 130);
    lv_obj_set_y(ui_Image2, 43);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -88);
    lv_obj_set_y(ui_Label9, -23);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "1000");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -28);
    lv_obj_set_y(ui_Label1, -23);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "100");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 24);
    lv_obj_set_y(ui_Label2, -23);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "10");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 97);
    lv_obj_set_y(ui_Label3, -23);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "0.1");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel13, 6);
    lv_obj_set_height(ui_Panel13, 6);
    lv_obj_set_x(ui_Panel13, -58);
    lv_obj_set_y(ui_Panel13, -68);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel13, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0xE6E3E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel14 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel14, 6);
    lv_obj_set_height(ui_Panel14, 6);
    lv_obj_set_x(ui_Panel14, -58);
    lv_obj_set_y(ui_Panel14, -55);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel14, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0xE6E3E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 148);
    lv_obj_set_y(ui_Label4, -23);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "0.01");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel16 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel16, 142);
    lv_obj_set_height(ui_Panel16, 104);
    lv_obj_set_x(ui_Panel16, -132);
    lv_obj_set_y(ui_Panel16, 147);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel17 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel17, 12);
    lv_obj_set_height(ui_Panel17, 12);
    lv_obj_set_x(ui_Panel17, -196);
    lv_obj_set_y(ui_Panel17, 223);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0x212020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel18 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel18, 12);
    lv_obj_set_height(ui_Panel18, 12);
    lv_obj_set_x(ui_Panel18, -178);
    lv_obj_set_y(ui_Panel18, 223);
    lv_obj_set_align(ui_Panel18, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0x212020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel19 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel19, 12);
    lv_obj_set_height(ui_Panel19, 12);
    lv_obj_set_x(ui_Panel19, -161);
    lv_obj_set_y(ui_Panel19, 223);
    lv_obj_set_align(ui_Panel19, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel19, lv_color_hex(0x212020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -80);
    lv_obj_set_y(ui_Label11, 223);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "VOLOS PROJECTS");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x191818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_line1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_line1, 9);
    lv_obj_set_height(ui_line1, 3);
    lv_obj_set_x(ui_line1, 178);
    lv_obj_set_y(ui_line1, -98);
    lv_obj_set_align(ui_line1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_line1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_line1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_line1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_line1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_line1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_line2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_line2, 5);
    lv_obj_set_height(ui_line2, 3);
    lv_obj_set_x(ui_line2, 180);
    lv_obj_set_y(ui_line2, -90);
    lv_obj_set_align(ui_line2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_line2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_line2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_line2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_line2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_line2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_line3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_line3, 9);
    lv_obj_set_height(ui_line3, 3);
    lv_obj_set_x(ui_line3, 178);
    lv_obj_set_y(ui_line3, -82);
    lv_obj_set_align(ui_line3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_line3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_line3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_line3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_line3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_line3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_line4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_line4, 5);
    lv_obj_set_height(ui_line4, 3);
    lv_obj_set_x(ui_line4, 180);
    lv_obj_set_y(ui_line4, -74);
    lv_obj_set_align(ui_line4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_line4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_line4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_line4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_line4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_line4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_line5 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_line5, 9);
    lv_obj_set_height(ui_line5, 3);
    lv_obj_set_x(ui_line5, 178);
    lv_obj_set_y(ui_line5, -66);
    lv_obj_set_align(ui_line5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_line5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_line5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_line5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_line5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_line5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_line6 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_line6, 5);
    lv_obj_set_height(ui_line6, 3);
    lv_obj_set_x(ui_line6, 180);
    lv_obj_set_y(ui_line6, -58);
    lv_obj_set_align(ui_line6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_line6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_line6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_line6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_line6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_line6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_line7 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_line7, 9);
    lv_obj_set_height(ui_line7, 3);
    lv_obj_set_x(ui_line7, 178);
    lv_obj_set_y(ui_line7, -50);
    lv_obj_set_align(ui_line7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_line7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_line7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_line7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_line7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_line7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_line8 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_line8, 5);
    lv_obj_set_height(ui_line8, 3);
    lv_obj_set_x(ui_line8, 180);
    lv_obj_set_y(ui_line8, -42);
    lv_obj_set_align(ui_line8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_line8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_line8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_line8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_line8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_line8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel21 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel21, 14);
    lv_obj_set_height(ui_Panel21, 10);
    lv_obj_set_x(ui_Panel21, 178);
    lv_obj_set_y(ui_Panel21, -31);
    lv_obj_set_align(ui_Panel21, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel21, lv_color_hex(0x8B0C08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Panel16, ui_event_Panel16, LV_EVENT_ALL, NULL);

}
